### ISSUE TITLE
Webpage not available error while login

### ISSUE THREAD

**Issue by ddalmia** [platanus/cordova-gigya#6]
Hi,

I am developing an application in phonegap which uses gigya for social login. However, I get "Webpage not available" error when ever I try to login. The application opens up the concerned social provider and displays the login screen. After putting the credentials I get this error. I have attached the screenshot of the error. If you need more details then please contact me.
![loginerror](https://cloud.githubusercontent.com/assets/10558429/6727581/2c4f6a08-cde0-11e4-909d-95a7b3a0aa73.png).

Appreciate if you can help early. It is a bit urgent.

Regards,
Deepak.

**Comment by agustinf** [comment]
Is that URL (the one you censored) really reaching your app?

**Comment by ddalmia** [comment]
It is not a URL. It is the package name of the hybrid android application. I cannot disclose the package name.

**Comment by agustinf** [comment]
I understand, but it is a URL after all... see [What is a url?](https://kb.iu.edu/d/adnz). 
I don't need to know the package name, but for what I see, Gigya is trying to reach your app from its website, so it uses a URL that is formed by putting the package name as the protocol... this way, the phone can open back the app once the user has logged in...
